[build]
  publish = "."
[functions]
  directory = "netlify/functions"
[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200
[[redirects]]
  from = "/api/dados"
  to = "/.netlify/functions/dados"
  status = 200
